### ISSUE TITLE
Rework branch

### ISSUE THREAD

**Issue by odahcam** [Leopoldthecoder/Perspective.js#1]
README says it's being reworked now, so it would be nice to have a branch with the new version in development.

**Comment by Leopoldthecoder** [comment]
You're right. Honestly I didn't expect anyone to find this tiny project of mine, so I got a bit lazy😂. Getting down to the new branch right now.

**Comment by odahcam** [comment]
😄 I also have an parallax repo: https://github.com/odahcam/jquery.parallax

I was looking for better parallax effects, if you want to take some code from my repo it's alright.

**Comment by Leopoldthecoder** [comment]
Awsome!
